### ISSUE TITLE
Auto function: only go to the next item when the current video has finished playing

### ISSUE THREAD

**Issue by Smile4ever** [ismaelpadilla/reddit-slideshow#24]
The auto function (every five seconds) is great, but it should not go to the next item yet when a video is still playing (for the first time).

**Comment by ismaelpadilla** [comment]
This is a great suggestion, I will release a new version of the site which addresses this shortly.

**Comment by ismaelpadilla** [comment]
New version is live and videos won't be skipped unless they have fully played at least once. Note that this will skip long gifs.
